import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();
import {
  User, Word, Sentence, Dictionary, DictionaryWord, StudySession, StudySessionWord,
  UserDictionaryConfig, UserWordProgress, UserSentenceProgress, SentencePracticeSession,
  SentencePracticeItem, LearningRecord, ReviewRecord
} from '../types/index.ts';
import { extractSentencePhrases } from '../utils/sentenceUtils.ts';

type Row = Record<string, any>;

const pool = mysql.createPool({
  host: process.env.DB_HOST || '127.0.0.1',
  port: Number(process.env.DB_PORT || 3307),
  user: process.env.DB_USER || 'linguastep',
  password: process.env.DB_PASSWORD || 'LinguaDB@123456',
  database: process.env.DB_NAME || 'linguastep',
  waitForConnections: true,
  connectionLimit: 10,
  charset: 'utf8mb4'
});

const iso = (v: any) => v ? new Date(v).toISOString() : undefined;
// MySQL 5.7 DATETIME does not accept ISO-8601 strings containing T/Z.
const mysqlDate = (v: any) => v ? new Date(v).toISOString().slice(0, 19).replace('T', ' ') : null;

class MySQLStorage {
  async findUserByEmail(email: string): Promise<User | undefined> {
    const [rows] = await pool.query('SELECT * FROM users WHERE LOWER(email)=LOWER(?) LIMIT 1', [email]);
    return this.user((rows as Row[])[0]);
  }
  async findUserByUsername(username: string): Promise<User | undefined> {
    const [rows] = await pool.query('SELECT * FROM users WHERE LOWER(username)=LOWER(?) LIMIT 1', [username]);
    return this.user((rows as Row[])[0]);
  }
  async findUserById(id: string): Promise<User | undefined> {
    const [rows] = await pool.query('SELECT * FROM users WHERE id=? LIMIT 1', [id]);
    return this.user((rows as Row[])[0]);
  }
  async createUser(user: User): Promise<User> {
    const c: UserDictionaryConfig = { id:`cfg-${Date.now()}`, userId:user.id, defaultDictionaryId:'dict-primary-6', sentenceDictionaryId:'dict-primary-6', englishDict:'Oxford', ecDict:'Oxford', phoneticType:'UK', audioType:'UK', enablePhonics:true, sentencePracticeCount:5, createdAt:new Date().toISOString(), updatedAt:new Date().toISOString() };
    const d: Dictionary = { id:`dict-user-${user.id}`, name:`${user.username}的生词本`, code:`vocab_${user.username}_${Date.now().toString(36)}`, description:'个人专属生词与高频复习词汇集', ownerType:'USER', ownerUserId:user.id, isSystem:false, isPublic:false, status:'ACTIVE', createdAt:c.createdAt, updatedAt:c.updatedAt };
    const conn=await pool.getConnection(); try { await conn.beginTransaction();
      await conn.query('INSERT INTO users(id,username,email,password_hash,role,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[user.id,user.username,user.email,user.passwordHash,user.role,mysqlDate(user.createdAt),mysqlDate(user.updatedAt)]);
      await conn.query('INSERT INTO dictionary(id,name,code,description,owner_type,owner_user_id,is_system,is_public,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[d.id,d.name,d.code,d.description,d.ownerType,d.ownerUserId,d.isSystem,d.isPublic,d.status,mysqlDate(d.createdAt),mysqlDate(d.updatedAt)]);
      await conn.query('INSERT INTO user_dictionary_config(id,user_id,default_dictionary_id,sentence_dictionary_id,phonetic_type,audio_type,enable_phonics,sentence_practice_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[c.id,c.userId,c.defaultDictionaryId,c.sentenceDictionaryId,c.phoneticType,c.audioType,c.enablePhonics,c.sentencePracticeCount,mysqlDate(c.createdAt),mysqlDate(c.updatedAt)]);
      await conn.commit(); return user;
    } catch(e){await conn.rollback();throw e} finally{conn.release()}
  }

  private user(r?:Row): User|undefined { if(!r)return; return {id:r.id,username:r.username,email:r.email,passwordHash:r.password_hash,role:r.role,createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}; }

  async getAllDictionaries(userId?: string) { const [rows]=await pool.query(`SELECT d.*,COUNT(dw.id) word_count FROM dictionary d LEFT JOIN dictionary_word dw ON dw.dictionary_id=d.id AND dw.is_active=1 WHERE d.status='ACTIVE' AND (d.is_system=1 OR d.is_public=1 OR d.owner_user_id=?) GROUP BY d.id ORDER BY d.created_at`,[userId||'']); return (rows as Row[]).map(this.dict); }
  async getUserDictionaries(userId:string){const [rows]=await pool.query(`SELECT d.*,COUNT(dw.id) word_count FROM dictionary d LEFT JOIN dictionary_word dw ON dw.dictionary_id=d.id AND dw.is_active=1 WHERE d.owner_type='USER' AND d.owner_user_id=? AND d.status<>'INACTIVE' GROUP BY d.id ORDER BY d.created_at`,[userId]);return(rows as Row[]).map(this.dict)}
  async getWordUserDictionaries(userId:string,wordId:string){const [rows]=await pool.query(`SELECT dw.dictionary_id FROM dictionary_word dw JOIN dictionary d ON d.id=dw.dictionary_id WHERE d.owner_type='USER' AND d.owner_user_id=? AND dw.word_id=? AND dw.is_active=1`,[userId,wordId]);return(rows as Row[]).map(r=>r.dictionary_id)}
  async getAdminDictionaries(){const [rows]=await pool.query(`SELECT d.*,COUNT(dw.id) word_count FROM dictionary d LEFT JOIN dictionary_word dw ON dw.dictionary_id=d.id AND dw.is_active=1 GROUP BY d.id ORDER BY d.created_at`);return(rows as Row[]).map(this.dict)}
  async findDictionaryById(id:string){const [rows]=await pool.execute(`SELECT d.*,COUNT(dw.id) word_count FROM dictionary d LEFT JOIN dictionary_word dw ON dw.dictionary_id=d.id AND dw.is_active=1 WHERE d.id=? GROUP BY d.id`,[id]);return this.dict((rows as Row[])[0])}
  private dict(r?:Row):any{if(!r)return;return{id:r.id,name:r.name,code:r.code,description:r.description||'',ownerType:r.owner_type,ownerUserId:r.owner_user_id,isSystem:Boolean(r.is_system),isPublic:Boolean(r.is_public),status:r.status,wordCount:Number(r.word_count||0),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  async createDictionary(d:Dictionary){await pool.query('INSERT INTO dictionary(id,name,code,description,owner_type,owner_user_id,is_system,is_public,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[d.id,d.name,d.code,d.description||'',d.ownerType,d.ownerUserId,d.isSystem,d.isPublic,d.status,d.createdAt,d.updatedAt]);return d}
  async updateDictionary(id:string,p:Partial<Dictionary>){const d=await this.findDictionaryById(id);if(!d)return;const x={...d,...p,updatedAt:new Date().toISOString()};await pool.query('UPDATE dictionary SET name=?,description=?,is_public=?,status=?,updated_at=? WHERE id=?',[x.name,x.description||'',x.isPublic,x.status,x.updatedAt,id]);return x}
  async deleteDictionary(id:string){const [r]=await pool.query('DELETE FROM dictionary WHERE id=?',[id]);return Number((r as any).affectedRows)>0}
  async getDictionaryWords(dictionaryId:string){const [rows]=await pool.query(`SELECT dw.id AS dw_id,dw.dictionary_id,dw.word_id,dw.sequence_no,dw.is_active,dw.definition_source,dw.created_at,w.id AS word_ref_id FROM dictionary_word dw JOIN word w ON w.id=dw.word_id WHERE dw.dictionary_id=? AND dw.is_active=1 ORDER BY dw.sequence_no`,[dictionaryId]);return Promise.all((rows as Row[]).map(async r=>({id:r.dw_id,dictionaryId:r.dictionary_id,wordId:r.word_id,sequence:r.sequence_no,isActive:Boolean(r.is_active),definitionSource:r.definition_source||undefined,createdAt:iso(r.created_at)!,word:await this.findWordById(r.word_id)})))}
  private dw(r:Row):DictionaryWord{return{id:r.id,dictionaryId:r.dictionary_id,wordId:r.word_id,sequence:r.sequence_no,isActive:Boolean(r.is_active),definitionSource:r.definition_source||undefined,createdAt:iso(r.created_at)!}}
  async addWordToDictionary(dictionaryId:string,wordId:string,sequence?:number){const [rows]=await pool.query('SELECT * FROM dictionary_word WHERE dictionary_id=? AND word_id=?',[dictionaryId,wordId]);let r=(rows as Row[])[0];if(r){await pool.query('UPDATE dictionary_word SET is_active=1 WHERE id=?',[r.id]);return this.dw({...r,is_active:1})}const [[m]]:any=await pool.query('SELECT COALESCE(MAX(sequence_no),0)+1 n FROM dictionary_word WHERE dictionary_id=?',[dictionaryId]);const x={id:`dw-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,dictionaryId,wordId,sequence:sequence??m.n,isActive:true,createdAt:new Date().toISOString()};await pool.query('INSERT INTO dictionary_word(id,dictionary_id,word_id,sequence_no,is_active,created_at) VALUES(?,?,?,?,?,?)',[x.id,dictionaryId,wordId,x.sequence,1,x.createdAt]);return x}
  async removeWordFromDictionary(dictionaryId:string,wordId:string){const [r]=await pool.query('DELETE FROM dictionary_word WHERE dictionary_id=? AND word_id=?',[dictionaryId,wordId]);return Number((r as any).affectedRows)>0}
  async batchAddWordsToDictionary(id:string,wids:string[]){const out=[];for(const w of wids){if(await this.findWordById(w))out.push(await this.addWordToDictionary(id,w))}return out}
  async getDictionaryConfig(userId:string){let [rows]=await pool.query('SELECT * FROM user_dictionary_config WHERE user_id=?',[userId]);let r=(rows as Row[])[0];if(!r){const now=new Date().toISOString();const id=`cfg-${Date.now()}`;await pool.query('INSERT INTO user_dictionary_config(id,user_id,default_dictionary_id,sentence_dictionary_id,phonetic_type,audio_type,enable_phonics,sentence_practice_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[id,userId,'dict-primary-6','dict-primary-6','UK','UK',1,5,now,now]);r={id,user_id:userId,default_dictionary_id:'dict-primary-6',sentence_dictionary_id:'dict-primary-6',phonetic_type:'UK',audio_type:'UK',enable_phonics:1,sentence_practice_count:5,created_at:now,updated_at:now}}return this.config(r)}
  private config(r:Row):UserDictionaryConfig{return{id:r.id,userId:r.user_id,defaultDictionaryId:r.default_dictionary_id||undefined,sentenceDictionaryId:r.sentence_dictionary_id||undefined,phoneticType:r.phonetic_type,audioType:r.audio_type,enablePhonics:Boolean(r.enable_phonics),sentencePracticeCount:Number(r.sentence_practice_count||5),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  async saveDictionaryConfig(userId:string,p:Partial<UserDictionaryConfig>){const c=await this.getDictionaryConfig(userId);const x={...c,...p,updatedAt:new Date().toISOString()};await pool.query('UPDATE user_dictionary_config SET default_dictionary_id=?,sentence_dictionary_id=?,phonetic_type=?,audio_type=?,enable_phonics=?,sentence_practice_count=?,updated_at=? WHERE user_id=?',[x.defaultDictionaryId||null,x.sentenceDictionaryId||null,x.phoneticType,x.audioType,x.enablePhonics,x.sentencePracticeCount||5,x.updatedAt,userId]);return x}

  async getAllWords(){const [rows]=await pool.query('SELECT * FROM word ORDER BY id');return Promise.all((rows as Row[]).map(r=>this.findWordById(r.id))) as any}
  async findWordById(id:string){const [rows]=await pool.execute('SELECT * FROM word WHERE id=?',[id]);return this.loadWord((rows as Row[])[0])}
  async findWordByText(text:string){const [rows]=await pool.query('SELECT * FROM word WHERE LOWER(text)=LOWER(?)',[text.trim()]);return this.loadWord((rows as Row[])[0])}
  private async loadWord(r?:Row):Promise<Word|undefined>{if(!r)return;const [m]=await pool.query('SELECT * FROM word_meaning WHERE word_id=? ORDER BY created_at',[r.id]);const [p]=await pool.query('SELECT * FROM word_phonics WHERE word_id=? ORDER BY sequence_no',[r.id]);return{id:r.id,text:r.text,phoneticUk:r.phonetic_uk||'',phoneticUs:r.phonetic_us||'',audioUkUrl:r.audio_uk_url||undefined,audioUsUrl:r.audio_us_url||undefined,pos:r.pos||'',difficulty:Number(r.difficulty||1),meanings:(m as Row[]).map(x=>({id:x.id,wordId:x.word_id,pos:x.pos,definitionCn:x.definition_cn,definitionEn:x.definition_en||undefined,exampleEn:x.example_en||undefined,exampleCn:x.example_cn||undefined})),phonics:(p as Row[]).map(x=>({id:x.id,wordId:x.word_id,sequence:x.sequence_no,text:x.text,phonetic:x.phonetic,syllable:x.syllable,audioUrl:x.audio_url||undefined}))}}
  async createWord(w:Word){const c=await pool.getConnection();try{await c.beginTransaction();await c.query('INSERT INTO word(id,text,phonetic_uk,phonetic_us,audio_uk_url,audio_us_url,pos,difficulty) VALUES(?,?,?,?,?,?,?,?)',[w.id,w.text,w.phoneticUk,w.phoneticUs,w.audioUkUrl||null,w.audioUsUrl||null,w.pos,w.difficulty]);for(const m of w.meanings)await c.query('INSERT INTO word_meaning(id,word_id,pos,definition_cn,definition_en,example_en,example_cn) VALUES(?,?,?,?,?,?,?)',[m.id,w.id,m.pos,m.definitionCn,m.definitionEn||null,m.exampleEn||null,m.exampleCn||null]);for(const p of w.phonics)await c.query('INSERT INTO word_phonics(id,word_id,sequence_no,text,phonetic,syllable,audio_url) VALUES(?,?,?,?,?,?,?)',[p.id,w.id,p.sequence,p.text,p.phonetic,p.syllable,p.audioUrl||null]);await c.commit();return w}catch(e){await c.rollback();throw e}finally{c.release()}}
  async getWordProgress(userId:string,wordId:string){const [rows]=await pool.query('SELECT * FROM user_word_progress WHERE user_id=? AND word_id=?',[userId,wordId]);return this.progress((rows as Row[])[0])}
  async getAllWordProgresses(userId:string){const [rows]=await pool.query('SELECT * FROM user_word_progress WHERE user_id=?',[userId]);return(rows as Row[]).map(this.progress)}
  private progress(r?:Row):UserWordProgress|undefined{if(!r)return;return{id:r.id,userId:r.user_id,wordId:r.word_id,status:r.status,learnCount:r.learn_count,reviewCount:r.review_count,correctCount:r.correct_count,wrongCount:r.wrong_count,streak:r.streak,mastery:r.mastery,lastLearnAt:iso(r.last_learn_at),lastReviewAt:iso(r.last_review_at),nextReviewAt:iso(r.next_review_at),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  async saveWordProgress(p:UserWordProgress){await pool.query(`INSERT INTO user_word_progress(id,user_id,word_id,status,learn_count,review_count,correct_count,wrong_count,streak,mastery,last_learn_at,last_review_at,next_review_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),learn_count=VALUES(learn_count),review_count=VALUES(review_count),correct_count=VALUES(correct_count),wrong_count=VALUES(wrong_count),streak=VALUES(streak),mastery=VALUES(mastery),last_learn_at=VALUES(last_learn_at),last_review_at=VALUES(last_review_at),next_review_at=VALUES(next_review_at),updated_at=VALUES(updated_at)`,[p.id,p.userId,p.wordId,p.status,p.learnCount,p.reviewCount,p.correctCount,p.wrongCount,p.streak,p.mastery,p.lastLearnAt||null,p.lastReviewAt||null,p.nextReviewAt||null,p.createdAt,p.updatedAt]);return p}
  async createStudySession(s:StudySession,words:StudySessionWord[]){const c=await pool.getConnection();try{await c.beginTransaction();await c.query("UPDATE study_session SET status='CANCELLED' WHERE user_id=? AND status='IN_PROGRESS'",[s.userId]);await c.query('INSERT INTO study_session(id,user_id,mode,dictionary_id,total_count,completed_count,exclude_mastered,sort_mode,status,current_word_index,started_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[s.id,s.userId,s.mode,s.dictionaryId,s.totalCount,s.completedCount,s.excludeMastered,s.sortMode,s.status,s.currentWordIndex,s.startedAt,s.createdAt,s.updatedAt]);for(const w of words)await c.query('INSERT INTO study_session_word(id,session_id,word_id,sequence_no,learn_status,write_status,completed,is_correct,user_input,learned_at,written_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[w.id,w.sessionId,w.wordId,w.sequence,w.learnStatus,w.writeStatus,w.completed,w.isCorrect,w.userInput,w.learnedAt,w.writtenAt,w.createdAt]);await c.commit();return s}catch(e){await c.rollback();throw e}finally{c.release()}}
  async findStudySessionById(id:string){const [ss]=await pool.query('SELECT * FROM study_session WHERE id=?',[id]);const s=(ss as Row[])[0];if(!s)return;const [ws]=await pool.query('SELECT * FROM study_session_word WHERE session_id=? ORDER BY sequence_no',[id]);const words=await Promise.all((ws as Row[]).map(async r=>({...this.sw(r),word:await this.findWordById(r.word_id)})));return{...this.session(s),words,dictionary:await this.findDictionaryById(s.dictionary_id)}}
  private session(r:Row):StudySession{return{id:r.id,userId:r.user_id,mode:r.mode,dictionaryId:r.dictionary_id,totalCount:r.total_count,completedCount:r.completed_count,excludeMastered:Boolean(r.exclude_mastered),sortMode:r.sort_mode,status:r.status,currentWordIndex:r.current_word_index,startedAt:iso(r.started_at)!,completedAt:iso(r.completed_at),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  private sw(r:Row):StudySessionWord{return{id:r.id,sessionId:r.session_id,wordId:r.word_id,sequence:r.sequence_no,learnStatus:r.learn_status,writeStatus:r.write_status,completed:Boolean(r.completed),isCorrect:r.is_correct===null?null:Boolean(r.is_correct),userInput:r.user_input,learnedAt:iso(r.learned_at)||null,writtenAt:iso(r.written_at)||null,createdAt:iso(r.created_at)!}}
  async getActiveSessionByUserId(userId:string){const [r]=await pool.query("SELECT id FROM study_session WHERE user_id=? AND status='IN_PROGRESS' ORDER BY updated_at DESC LIMIT 1",[userId]);const id=(r as Row[])[0]?.id;return id?this.findStudySessionById(id):undefined}
  async updateStudySession(s:StudySession){await pool.query('UPDATE study_session SET completed_count=?,status=?,current_word_index=?,completed_at=?,updated_at=? WHERE id=?',[s.completedCount,s.status,s.currentWordIndex,s.completedAt||null,s.updatedAt,s.id]);return s}
  async updateStudySessionWord(w:StudySessionWord){await pool.query('UPDATE study_session_word SET learn_status=?,write_status=?,completed=?,is_correct=?,user_input=?,learned_at=?,written_at=? WHERE id=?',[w.learnStatus,w.writeStatus,w.completed,w.isCorrect,w.userInput,w.learnedAt||null,w.writtenAt||null,w.id]);return w}

  async getAllSentences(){const [r]=await pool.query('SELECT id FROM sentence ORDER BY id');return Promise.all((r as Row[]).map(x=>this.findSentenceById(x.id))) as any}
  async findSentenceById(id:string){const [r]=await pool.execute('SELECT * FROM sentence WHERE id=?',[id]);const s=(r as Row[])[0];if(!s)return;const [sw]=await pool.query('SELECT sw.position_no,w.id FROM sentence_word sw JOIN word w ON w.id=sw.word_id WHERE sw.sentence_id=? ORDER BY sw.position_no',[id]);const [st]=await pool.query('SELECT * FROM sentence_step WHERE sentence_id=? ORDER BY step_number',[id]);const [an]=await pool.query('SELECT * FROM sentence_analysis WHERE sentence_id=? ORDER BY start_position',[id]);return{id:s.id,content:s.content,translation:s.translation,level:s.level,audioUrl:s.audio_url||undefined,difficulty:s.difficulty,steps:(st as Row[]).map(x=>({id:x.id,sentenceId:id,stepNumber:x.step_number,content:x.content,translation:x.translation,phonetic:x.phonetic||undefined,type:x.type,audioUrl:x.audio_url||undefined})),analyses:(an as Row[]).map(x=>({id:x.id,sentenceId:id,text:x.text,startPosition:x.start_position,endPosition:x.end_position,type:x.type,explanation:x.explanation}))}}
  async getSentenceProgress(userId:string,sentenceId:string){const[r]=await pool.query('SELECT * FROM user_sentence_progress WHERE user_id=? AND sentence_id=?',[userId,sentenceId]);return this.usp((r as Row[])[0])}
  private usp(r?:Row):UserSentenceProgress|undefined{if(!r)return;return{id:r.id,userId:r.user_id,sentenceId:r.sentence_id,status:r.status,currentStep:r.current_step,completedAt:iso(r.completed_at),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  async saveSentenceProgress(p:UserSentenceProgress){await pool.query('INSERT INTO user_sentence_progress(id,user_id,sentence_id,status,current_step,completed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),current_step=VALUES(current_step),completed_at=VALUES(completed_at),updated_at=VALUES(updated_at)',[p.id,p.userId,p.sentenceId,p.status,p.currentStep,p.completedAt||null,p.createdAt,p.updatedAt]);return p}
  async addLearningRecord(r:LearningRecord){await pool.query('INSERT INTO learning_record(id,user_id,item_type,item_id,action,is_correct,input_text,time_spent_sec,created_at) VALUES(?,?,?,?,?,?,?,?,?)',[r.id,r.userId,r.itemType,r.itemId,r.action,r.isCorrect,r.inputText||null,r.timeSpentSec,r.createdAt]);return r}
  async getLearningRecords(userId:string){const[r]=await pool.query('SELECT * FROM learning_record WHERE user_id=? ORDER BY created_at');return(r as Row[]).map(x=>({id:x.id,userId:x.user_id,itemType:x.item_type,itemId:x.item_id,action:x.action,isCorrect:Boolean(x.is_correct),inputText:x.input_text||undefined,timeSpentSec:x.time_spent_sec,createdAt:iso(x.created_at)!}))}
  async addReviewRecord(r:ReviewRecord){await pool.execute('INSERT INTO review_record(id,user_id,word_id,interval_days,next_review_at,result,created_at) VALUES(?,?,?,?,?,?,?)',[r.id,r.userId,r.wordId,r.intervalDays,r.nextReviewAt,r.result,r.createdAt]);return r}

  async createSentencePracticeSession(s:SentencePracticeSession,items:SentencePracticeItem[]){const c=await pool.getConnection();try{await c.beginTransaction();await c.query("UPDATE sentence_practice_session SET status='CANCELLED' WHERE user_id=? AND status='IN_PROGRESS'",[s.userId]);await c.query('INSERT INTO sentence_practice_session(id,user_id,dictionary_id,difficulty,total_count,current_sentence_index,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',[s.id,s.userId,s.dictionaryId||null,s.difficulty,s.totalCount,s.currentSentenceIndex,s.status,s.createdAt,s.updatedAt]);for(const i of items)await c.query('INSERT INTO sentence_practice_item(id,session_id,sentence_id,sequence_no,current_phase,current_phrase_index,completed,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',[i.id,i.sessionId,i.sentenceId,i.sequence,i.currentPhase,i.currentPhraseIndex,i.completed,i.createdAt,i.updatedAt]);await c.commit();return s}catch(e){await c.rollback();throw e}finally{c.release()}}
  async findSentencePracticeSessionById(id:string){const[r]=await pool.query('SELECT * FROM sentence_practice_session WHERE id=?',[id]);const s=(r as Row[])[0];if(!s)return;const[it]=await pool.query('SELECT * FROM sentence_practice_item WHERE session_id=? ORDER BY sequence_no',[id]);const items=await Promise.all((it as Row[]).map(async x=>{const sentence=await this.findSentenceById(x.sentence_id);return{...this.spi(x),sentence,phrases:sentence?extractSentencePhrases(sentence):[]}}));return{...this.sps(s),items}}
  private sps(r:Row):SentencePracticeSession{return{id:r.id,userId:r.user_id,dictionaryId:r.dictionary_id||undefined,difficulty:r.difficulty,totalCount:r.total_count,currentSentenceIndex:r.current_sentence_index,status:r.status,createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  private spi(r:Row):SentencePracticeItem{return{id:r.id,sessionId:r.session_id,sentenceId:r.sentence_id,sequence:r.sequence_no,currentPhase:r.current_phase,currentPhraseIndex:r.current_phrase_index,completed:Boolean(r.completed),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!}}
  async getActiveSentencePracticeSession(userId:string){const[r]=await pool.query("SELECT id FROM sentence_practice_session WHERE user_id=? AND status='IN_PROGRESS' ORDER BY updated_at DESC LIMIT 1",[userId]);const id=(r as Row[])[0]?.id;return id?this.findSentencePracticeSessionById(id):undefined}
  async updateSentencePracticeSession(s:SentencePracticeSession){await pool.query('UPDATE sentence_practice_session SET current_sentence_index=?,status=?,updated_at=? WHERE id=?',[s.currentSentenceIndex,s.status,s.updatedAt,s.id]);return s}
  async updateSentencePracticeItem(i:SentencePracticeItem){await pool.query('UPDATE sentence_practice_item SET current_phase=?,current_phrase_index=?,completed=?,updated_at=? WHERE id=?',[i.currentPhase,i.currentPhraseIndex,i.completed,i.updatedAt,i.id]);return i}
  async cancelSentencePracticeSession(id:string,userId:string){const[r]=await pool.query('UPDATE sentence_practice_session SET status=\'CANCELLED\',updated_at=NOW() WHERE id=? AND user_id=?',[id,userId]);return Number((r as any).affectedRows)>0}
}
export const db = new MySQLStorage();
